# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

os:
  - linux
  - osx

r:
  - release
  - devel
  
matrix:
  exclude:
    - r: devel
      os: osx

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - HDF5_VERSION=1.8.17
    - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"


warnings_are_errors: false
