# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GETmean <- function(X) {
    .Call('_iCellR_GETmean', PACKAGE = 'iCellR', X)
}

GETord <- function(x) {
    .Call('_iCellR_GETord', PACKAGE = 'iCellR', x)
}

rowSumsC <- function(x) {
    .Call('_iCellR_rowSumsC', PACKAGE = 'iCellR', x)
}

